name: Moonshot CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-moonshot:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - name: Checkout forked moonshot
        uses: actions/checkout@v3
        with:
          repository: ${{ vars.GH_MOONSHOT_CI_REPO_LOC }}
          ref: 'main'
          path: moonshot-data
          token:  ${{ secrets.ACTIONS_GITHUB_TOKEN }}

      - name: Setup Moonshot
        run: |
          chmod +x moonshot-data/.github/scripts/setup_ms_script.sh
          ./moonshot-data/.github/scripts/setup_ms_script.sh

      - name: Run Moonshot
        run: |
          chmod +x moonshot-data/.github/scripts/run_ms_script.sh
          ./moonshot-data/.github/scripts/run_ms_script.sh
        env:
          COOKBOOK_RUN_NAME: testcookbookrun-${{ github.run_id }}
          MOONSHOT_RUN_COOKBOOKS_LIST: |
            ${{ vars.COOKBOOK_RUN }}
          MOONSHOT_UPDATE_ENDPOINTS_LIST: |
            ${{ secrets.AZURE_OPENAI_4O_UPDATE_ENDPOINT }};${{ secrets.TOGETHER_LLAMA3_8B_CHAT_UPDATE_ENDPOINT }};${{ secrets.TOGETHER_LLAMA_GUARD_7B_UPDATE_ENDPOINT }}

      - name: Display Results
        run: |
          chmod +x moonshot-data/.github/scripts/display_ms_script.sh
          ./moonshot-data/.github/scripts/display_ms_script.sh
        env:
          COOKBOOK_RUN_NAME: testcookbookrun-${{ github.run_id }}

      - name: Commit Results
        run: |
          cd moonshot-data/
          # Configure git user for committing changes
          git config --global user.email "ci@example.com"
          git config --global user.name "CI Bot"
          # Add generated output files to the commit
          git add -f ./generated-outputs/*
          # Show git status
          git status
          # Commit the changes with a message including the pipeline ID
          git commit -m "Update generated files [ci skip] - Pipeline ID ($GITHUB_RUN_ID)"
          # Push the changes to the repository, skipping CI for this push
          git push -o ci.skip
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}